version: '3'
services:
  postgresql:
    image: postgres:11
    container_name: pdaily_postgres
    restart: unless-stopped
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_DB=sonarcloud
